### ISSUE TITLE
Transfer my website repo to rbind

### ISSUE THREAD

**Issue by martinolmos** [rbind/rbind.io#1]
Hi,

Hi, my name is Martin, I'm from Argentina, and I'm new to data science and R.
I'm making my website with blogdown and Hugo and would like to join Rbind.

Thanks,
Martin

**Comment by yihui** [comment]
I have sent the invite. Next time please use this repo instead: https://github.com/rbind/support/issues

**Comment by martinolmos** [comment]
Thanks!

Sent from Mail for Windows 10
